name: 🧪 test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install uv
        uses: astral-sh/setup-uv@v8
      - name: install dependencies
        run: uv sync --frozen --python ${{ matrix.python }}
      - name: build
        run: uv build
      - name: twine check
        run: uv run twine check dist/*
      - name: lint
        run: uv run flake8 cpast tests
      - name: test
        run: uv run pytest tests
